//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuricorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int Id { get; set; }
        public string CodigoReserva { get; set; }
        public Nullable<System.DateTime> FechaReserva { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<int> IdVehiculoCiudad { get; set; }
        public Nullable<int> IdCiudad { get; set; }
        public Nullable<int> IdPais { get; set; }
        public int Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
